### PR TITLE
Update plugins versions

### PR DESCRIPTION
**Pull request by pomadchin**
## Overview

This PR updates sbt and other plugins. The critical thing here is sbt-scapegoat plugin update as in the current master it doesn't work.

### CODE REVIEW

**Comment by metasim** [comment]
@pomadchin Did you test the bench plugin to make sure it works with the new version of JMH?

**Comment by pomadchin** [comment]
@metasim nope, that's why it's not merged yet

**Comment by pomadchin** [comment]
@metasim it looks like it works fine with a new JMH, can you throw here some parameters to check it better?

**Comment by pomadchin** [comment]
This PR requires no CQs as adds no extra deps into geotrellis artifacts.

**Pull request merged**
