### PR TITLE
update pureconfig to version 0.10.2

### PR DESCRIPTION
**Pull request by kwark**
## Overview

Updates pureconfig to version 0.10.2

### Checklist

- [x] PureConfig 0.10.2 # [CQ 19572](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19572)

### CODE REVIEW

**Comment by pomadchin** [comment]
Hey! Congratulations with your first contribution! However, could you sign eclipse CLA? 
https://www.eclipse.org/legal/ECA.php After doing that do `git commit —amend -S` and force push it. Also I’ll create a CQ for it as it’s required by eclipse.

**Comment by pomadchin** [comment]
Ah, that should be a small letter `-s`, that's a typo ):. 

```
git commit --amend -s && git push origin -f pureconfig
```

**Comment by kwark** [comment]
@pomadchin sign-off worked, anything else I need to do?

**Comment by pomadchin** [comment]
Nope, all good! It will be merged in soon and released in terms of 3.0 release I suppose. Thanks!

**Pull request merged**
