### PR TITLE
Remove `vectortile` from Core GeoTrellis

### PR DESCRIPTION
**Pull request by fosskers**
### TODO
- [x] Move code into new repository
- [x] Remove mentions of `vectortile` from config/README
- [x] Fix Travis

### Motivation
We recently decided that the `vectortile` subproject is not core GeoTrellis per se, but is something built with it. As such, it should be moved out of this repo to help better define the edges of Core GeoTrellis.

See #1991 .

### CODE REVIEW

**Comment by fosskers** [comment]
This will have to be redone if I make changes to `vectortile` while working on `vectorpipe`.

**Comment by pomadchin** [comment]
@fosskers would it be hard to bump up scalapb dp? https://github.com/locationtech/geotrellis/blob/master/vectortile/build.sbt#L7

**Comment by fosskers** [comment]
Not sure, I'll have to check. Is it messing things up?

**Comment by pomadchin** [comment]
Yep, looks like api changes on minor upgrade ._.

**Comment by fosskers** [comment]
#2038

**Comment by echeipesh** [comment]
After some internal discussion `vectortile` package is going to remain in geotrellis project because it is enough of a core datatype that is related to the way we work with geospatial data in GeoTrellis.

**Pull request closed without merging**
