### PR TITLE
Change aspect result to azimuth

### LINKED ISSUE #2580: Aspect result incorrect
As the notes in focal/Aspect.scala: "Aspect is computed in degrees from due north, i.e. as an azimuth in degrees not radians.", the aspect result needs to start from due north, and be clockwise.
However the present result starts from east, and is anti-clockwise.

### PR DESCRIPTION
**Pull request by Frophie**
## Overview

Change aspect result to azimuth, i.e. start from due north and be clockwise. So that it will match the API description in `raster.mapalgebra.focal.Aspect`.

### Checklist

- [x] `docs/CHANGELOG.rst` updated, if necessary
- [x] Unit tests added for bug-fix or new feature

Closes #2580

### CODE REVIEW

**Comment by Frophie** [comment]
@pomadchin Actually the problem is I have two emails under github account, I signed the ECA with gmail first, but turns out need to sign the qq-mail. Any way, I signed both of them now. 
About the signed-off-by, it is gmail automatic, don't know whether this is right.

**Comment by pomadchin** [comment]
Hm looks like `geotrellis.raster.mapalgebra.focal.AspectSpec` is still failing

**Comment by Frophie** [comment]
@pomadchin Yes, didn't replace the gdal compare file yet.

**Comment by pomadchin** [comment]
Thanks for your contribution :+1:! I want to summon @echeipesh mb he has opinions on how to merge this fix.

**Pull request merged**
