### PR TITLE
[WIP] Point Cloud

### PR DESCRIPTION
**Pull request by jamesmcclain**
- [ ] Finalized `PointCloud` representation
   - [ ] General buffering code should probably not be in `BufferTile`
   - [x] Avoid use of `Point` objects in `PointCloud` data structure
   - [ ] locationtech/geotrellis#1816
   - [ ] locationtech/geotrellis#1821

### CODE REVIEW

**Comment by jamesmcclain** [comment]
> I am curious, should be point data in a raster package? mb to create a separate package? (at least package); another question is where to put necessary input formats.

All good questions.  The placement of the various components are all provisional.  It probably does make sense to put this stuff, including the new input formats, into a separate project.

**Comment by pomadchin** [comment]
I believe it makes sense to have a look into our [PDAL JNI](https://github.com/PDAL/PDAL/pull/1371) bindings API: https://github.com/pomadchin/PDAL/blob/fdcc55ac90374a5283277e414bf0aa2254afc76e/java/tests/src/test/scala/io/pdal/PackedPointsSpec.scala

**Comment by jamesmcclain** [comment]
> I believe it makes sense to have a look into our PDAL JNI bindings API: https://github.com/pomadchin/PDAL/blob/fdcc55ac90374a5283277e414bf0aa2254afc76e/java/tests/src/test/scala/io/pdal/PackedPointsSpec.scala

Thanks for the pointer.  Since this stuff depends on your work, it might make sense for me to rebase my work on top of yours.

**Comment by jamesmcclain** [comment]
I will leave this pull request open for continued visibility.

**Comment by pomadchin** [comment]
@jamesmcclain I'll create a separate project in a couple of minutes with PDAL dep, after that you can rebase (that's a good idea i think)

**Pull request closed without merging**
