### PR TITLE
ASCII art renderer for terminal-based qualitative evaluation

### PR DESCRIPTION
**Pull request by metasim**
When working with tiles in the spark shell (or other REPL-like environment), sometimes it's nice to get an on-the-fly qualitative visualization of what you're looking at without rendering to an image. This has become even more pertinent during the development of RasterFrames. Here's an example:

```
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘████  ∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘█████  ████    ∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘████████████▜   █▜     ∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘█████▖▖▖▖█████▖▖  █           ∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘██████████▜▖ ▖██▖█▖  ▖██             ∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘████████████▜▖▖▖▖▖███▖▖▖▖▖ █▖ █            ∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘██████████████████████▖ █████   ▜█ ██            ∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘████████████████████▜▜███▖▜█████                      ∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘████████████████████████▜█▜███████                         ∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘████████████████████████████▜▖▖██████▖                           ∘∘∘∘∘∘∘
∘∘∘∘██████████████████████████████▖▖▖    ▜▜▖▖  ▖ ▖    ▖                  ∘∘∘∘∘∘∘
█████████████████████████████▜██▜▖▜▜▖                 ███                 ∘∘∘∘∘∘
████████████████████████████▜█▖█▜▚▜▜▖▖ ▖   ▖           ▖▖     ▖           ∘∘∘∘∘∘
██████████████████████████████▜▚▜▚▜█▖▖▖▖▖▖▖▖▖  ▖▖▖▖▖▖▖▖▖▖   ▖▖ ▖▖          ∘∘∘∘∘
∘█████████████████████████████▜▚▚▚▚▖▖▚▚▚▚▖▖█▖  ▖▖▖▖▚█▜█▜▜▖▖       ▖        ∘∘∘∘∘
∘████████████▜█████████████████▚▚▜▜▚▜▜▜▖▚▚▖▖▖▖▚▚▚█████████▜▖▖▖▖▖            ∘∘∘∘
∘█████████████▖████████████████▚▚▜▜▜▚▚▚▚▚▚▚▚▚▖▜████████████████▖▖  ▖  ▖     ∘∘∘∘
∘∘█████████████████████████████▚▚▚▜▚▚▚▚▜▜▜▜▜▚▚████████████████▖▖▖   ▖▖▖▖▖▖   ∘∘∘
∘∘███████████████████████████▜█▚▚▚▚▚▜▜▜▜▜▜▜▜▜▚█████████▜▜▜▜▖▖▖▖▖▖  ▖▖█▜▜█▖   ∘∘∘
∘∘▖▖████████████████████████▚▚▜▜▚▚▚▚▜▜▜▜▜▜▜▜▜▜▜█████▜▜▜▜▚▚▚▚▚▚▚▖▖▚▚▖▜██▖▖ ▖  ∘∘∘
∘∘∘█████████████████████████▜▚▚▚▚▚▚▚▜▜▜▜▜▜▜▜▜▚██▜▜██▜▜▜▜▜▜▜█▖▚▚▖▖██████▖▖▖▖   ∘∘
∘∘∘▖███████████████████████▚▚▚▚▜▚▚▚▚▜▜▜▜▜▜▜▜▚▚▚███▚▜▜▜▜▜█████▜▚▚▚██████▖▜█▜▜  ∘∘
∘∘∘█████████████████████████▚▜▚▚▚▚▚▚▜▜▜▜▜▚▚▚▚▚▚▜▜▜██▚▜██▚▜▜█▜▜▜████████████▖  ∘∘
∘∘∘∘ ▖██████████████████████▚▜▜▚▚▚▚▚▚▚▚▚▚▖▚▚▚▚▚▚▚▚▚▜█▚█▚▜▜▜▚▚▚█████████████▖   ∘
∘∘∘∘  ▖████████▖▖████████████▜▚▜▚▚▚▚▚▚▚▜▚▖▚▚▚▚▚▚▚▚▜▚▜▚▜▜▚▖▖▜▜▜▜▚▜▚███████████  ∘
∘∘∘∘∘  ▖███████▜▚▚▖▖██████████▜▜▚▜▚▚▜▚▚▚▜▜▚▚▚▜▜▜█▚▚▚▚▚▚██▜█▚▜▜▚▚▚▚▚▚▜████████▜ ∘
∘∘∘∘∘     ▖▖▖▖█▜▖▖▖▖▖█████████▚▜▜▜▜▚▚▚▚▚▚▚▜▜▜▚▜█▜████▚▜████▚▚▜▜▚▚█████████ ██▜ ▜
∘∘∘∘∘  ▜▖▖▜▜▖▖▖▖▖▖▖▖▖███████████▚▚▚▜▚▚▚▚▚▚▚▜▜▜▚█▚▚██▜██████▜▚▚▚█████████▖█▜█████
∘∘∘∘∘∘  ▖█▖▖▖▖▖▖▖ ▖▖▖▖▖▖█████████▜▜▚▚▚▚▖▚▚▚▚▚▚▚▚▜████████████████████▖▖▖██▖█████
∘∘∘∘∘∘     ▖      ▖▜████▜█████████▜▚▚███████▜█████▜██████████████████▖█▜▖████∘∘∘
∘∘∘∘∘∘∘          ▖███▜█▖  ▖████▚▖██▚▚▜███████████████▚████████▜▖█████████∘∘∘∘∘∘∘
∘∘∘∘∘∘∘                        ▖▖▖▚▖▜▜███████████████████████████████∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘                       ▖▖▖▖▜████████████████████████████∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘                        ▖▖▖▖██████▜████████████████∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘                        ▖▖▖▖▜██▖    ▖▖▜▜█████∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘                         ▖▜▖ ▖        ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘                               ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘            ▖           ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘                ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘      ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
```

In addition to providing this capability, this PR refactors the existing numerical `asciiDraw` functionality, pulling it out of `Tile` and into a set of extension methods, providing better separation of concerns and normalizing it compared to the other rendering methods. It should remain source backward compatible, but is likely *not* binary backward compatible, and is therefore more a candidate for 2.0. I could submit a separate PR with only the ASCII art functionality if that is preferred.

### CODE REVIEW

**Comment by metasim** [comment]
Here's what it looks like using the `HATCHING` palette instead of `STIPLED' :

```
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘####  ∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘#####  ####    ∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘#############   ##     ∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘##### .  ##### .  #           ∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘###########.  ## #   .##             ∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘#############,..  ###      #  #            ∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘######################  #####   ## ##            ∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘#########################.######                      ∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘∘##################################                         ∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘#############################. ######.                           ∘∘∘∘∘∘∘
∘∘∘∘##############################,.     ##                              ∘∘∘∘∘∘∘
#################################;##.                 ###                 ∘∘∘∘∘∘
##############################;##+x#.  .   .           ..                 ∘∘∘∘∘∘
###############################-#-x#,.....;,   .,....,,,.                  ∘∘∘∘∘
∘##############################-++-,;-=--;;#.  ..,;=####x;.                ∘∘∘∘∘
∘##############################-=xx=x##;-;,..,--=##########,,,.             ∘∘∘∘
∘#############,################-=xxx+=-+-----;#################             ∘∘∘∘
∘∘#############################-=;#-+--XXXXX=-################..    .,....   ∘∘∘
∘∘#############################--==+xXXXXXXXX-#########xxx#,,;;,.  ,;####    ∘∘∘
∘∘  ########################-+xx+++=xXXXXXXXXXX######Xxx++==--;;;;;;### .    ∘∘∘
∘∘∘##########################+==++==xXXXXXXXX+###x##xXxxXx##;+;;;######.. .   ∘∘
∘∘∘ #######################-=+=x++==xxXXXXXX+-+###+xXxX#######-;=######,####  ∘∘
∘∘∘#########################+#-++==+xxxxx---=-=##X##-###=#x##x#############   ∘∘
∘∘∘∘  ######################+xx===+====+-;-====-=-=##;#-#xx==-#############.   ∘
∘∘∘∘   ########;,############x+x+-+=-++x-;-+++-=+-x-#=x#+;;##xx+x=###########  ∘
∘∘∘∘∘   ########-;,,##########xx+x=-x=+=xx+++x###--===-####=xx++=-==x######### ∘
∘∘∘∘∘      .,,##,,,,,#########+xxxx===+==+xxx+#######=#####-=xx+=######### ### #
∘∘∘∘∘  #..##,;;,,.,..###########+-=x==+++=-xxx+#+-##########-+=######### #######
∘∘∘∘∘∘  .#. ..... .   .,#########xx+==-;++====+=#####################  .##,#####
∘∘∘∘∘∘             ###############x+;#######x########################.## ####∘∘∘
∘∘∘∘∘∘∘           #####   .####;,##-;################;#########;#########∘∘∘∘∘∘∘
∘∘∘∘∘∘∘                        .,,-;#################################∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘                        ,;;#############################∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘                        .,,,#######################∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘                         .,.###      .#######∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘                          #           ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘                               ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘                        ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘                ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
∘∘∘∘∘∘∘∘∘∘∘∘      ∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘∘
```

**Comment by lossyrob** [comment]
Whaaaaat this is awesome!

**Comment by lossyrob** [comment]
> but is likely not binary backward compatible

Is this going to be a problem for 1.2 @echeipesh ?

**Comment by echeipesh** [comment]
This is pretty awesome but remove a method from `Tile` interface definitely breaks binary compatibility.

**Comment by metasim** [comment]
@lossyrob & @echeipesh , I reverted back the refactoring code, and created a new issue #2366 to reflect my desire to unclutter `Tile`.

**Comment by lossyrob** [comment]
> definitely breaks binary compatibility.

Are we maintaining binary compatibility between minor versions?

**Comment by echeipesh** [comment]
@lossyrob Yes, keeping binary compatibility with minor and breaking it with major.

**Pull request merged**
