### PR TITLE
Remove -Ymacro-expand:none flag

### PR DESCRIPTION
**Pull request by pomadchin**

### CODE REVIEW

**Comment by lossyrob** [comment]
What's going on with this change?

**Comment by pomadchin** [comment]
@lossyrob with this flag updated unidocs plugin can't access lenses in raster package: https://travis-ci.org/locationtech/geotrellis/jobs/203502868 
If it's quite important we can rollback unidocs plugin back.

**Comment by lossyrob** [comment]
Isn't important, since it's just in the aggregate project. Just deserved a little bit of explaining :)

**Comment by pomadchin** [comment]
@lossyrob ufff :D I was afraid i broke smth i could not catch, as I checked multiple times my local generated docs after that change and could not find difference.

**Pull request merged**
