### PR TITLE
Merge test projects

### PR DESCRIPTION
**Pull request by echeipesh**
Resolves https://github.com/locationtech/geotrellis/issues/2058

`scalacOptions ++= Seq("-optimize")` in `raster/build.sbt` appears to be the culprit for NPE seen in https://github.com/sbt/sbt/issues/3023

### CODE REVIEW

**Comment by echeipesh** [comment]
Did some benchmarks using https://github.com/locationtech/geotrellis/pull/2365

`optimized` benchmark is benchmark of PR #2365 and `non-optimized` is benchmark of this PR with #2365 merged into it.

https://gist.github.com/echeipesh/b555da8d12c79b65a5f58c98aed0be69

The files can be visualized using: http://jmh.morethan.io

But here is the interesting result: (`non-optimized` -> `optimized`)
screen shot 2017-09-29 at 11 52 12 am
screen shot 2017-09-29 at 11 52 28 am

Googling around reveals that `-optimize` is suspect in scalac `2.11`

> However, there are some known bugs in the 2.11.8 optimizer that we're only planning to fix with the rewrite in 2.12.0.

**Comment by fosskers** [comment]
Files changed: 2,045. :beer:

**Comment by metasim** [comment]
@echeipesh This is awesome! Glad to know about that visualization tool! Should we change the default output format to json?

**Comment by echeipesh** [comment]
Yes, I think that makes sense. Being able to drop them in and get a visual report is way more useful than being able to parse the results. There doesn't seem to be a pre-made way to convert between the formats either.

**Comment by metasim** [comment]
Changed the  default JSON:

https://github.com/locationtech/geotrellis/pull/2365/commits/c1b4d6e0b07816b8749570d4d97f9dbe6835a0b3

**Comment by metasim** [comment]
🎉

**Pull request merged**
