### PR TITLE
1.2 Changelog additions

### PR DESCRIPTION
**Pull request by fosskers**
### TODO

- [x] Thanks to new contributors
- [x] Entries for small API additions
- [x] Detailed entry for View Shed
- [x] Detailed entry to Euclidean Distance
- [x] Detailed entry for `ClipToGrid`

### CODE REVIEW

**Comment by fosskers** [comment]
https://github.com/locationtech/geotrellis/pull/2028 and https://github.com/locationtech/geotrellis/pull/2197 remain to be deciphered.

**Comment by fosskers** [comment]
Need to talk to @jamesmcclain on Monday about the parameters to `Viewshed` .

**Comment by echeipesh** [comment]
This is the prettiest change log I have ever seen, thank you.

**Comment by rossbernet** [comment]
Agreed. This is a beauty. Nice work @fosskers

**Pull request merged**
