### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rossbernet**
update mailing list link to locationtech in CONTRIBUTING.md

### CODE REVIEW

**Comment by lossyrob** [comment]
This CONTRIBUTING is out of sync with the doc one. Can we symlink the docs/contributing.rst to the root folder instead?

**Comment by rossbernet** [comment]
> Also in place edits make ip-validation unhappy
yeah I see that.

> Can we symlink the docs/contributing.rst to the root folder instead?
I don't know how to do that. Is there an example I can follow?

**Comment by lossyrob** [comment]
Symlinking can be done in the root of the repo by running `ln -s docs/contributing.rst CONTRIBUTING.rst`.

**Comment by moradology** [comment]
+1

**Pull request merged**
