### PR TITLE
Updated the Intro to Spark ETL Doc

### PR DESCRIPTION
**Pull request by lossyrob**
Fixes #1820 after the locationtech repo move.

### CODE REVIEW

**Comment by lossyrob** [comment]
@jbouffard can you update this?

**Comment by jbouffard** [comment]
@lossyrob here's the updated version #1887

**Comment by lossyrob** [comment]
@jbouffard hmm still is conflicting, did something merge in the last hour that caused a new conflict?

**Comment by fosskers** [comment]
`spark-etl-intro` doesn't exist anymore, any changes to it should be made in `etl.md`.

**Comment by lossyrob** [comment]
It was updated in a new PR, my bad.

**Pull request closed without merging**
