### PR TITLE
S3InputFormat - bucket names support period and dashes

### PR DESCRIPTION
**Pull request by ehochmuth**
Fixes #2133

### CODE REVIEW

**Comment by ehochmuth** [comment]
Just noticed ConfigFormats in spark-etl has the same problem.

**Comment by lossyrob** [comment]
Thanks for the contribution! Appreciate the consideration about alternate solutions, but I think the approach you took is the most simple and sound.

Can you sign a Eclipse Committer Agreement? The instructions to do so are here: http://geotrellis.readthedocs.io/en/latest/contributing.html#eclipse-contributor-agreement-eca. 

Let me know if you have any questions!

**Comment by ehochmuth** [comment]
Done. Do I need to do anything to re-trigger the ECA check on the PR?

**Comment by lossyrob** [comment]
No, the validation is being strange so it is failing everyone.

The other thing that's a bit more annoying is that Eclipse needs contributors to do a "sign-off" on the commits; it's described second paragraph here: http://geotrellis.readthedocs.io/en/latest/contributing.html#pull-requests.

Can you add the sign offs on the commits? After that I'm :+1: to merge

**Comment by ehochmuth** [comment]
added sign offs to commits

**Comment by pomadchin** [comment]
@ehochmuth oh; sign off means `sign off header`, like in [this](https://github.com/locationtech/geotrellis/pull/2131/commits/2b62725ff39490d38ca06bf414c7c18c6b43d94f) commit. It can be achieved by using `-s` flag: `git commit -s -m "msg"`.

**Comment by ehochmuth** [comment]
Ok rebased and ran git commit -s -S --amend -m "Author: Erich Hochmuth" for
both commits and then git push origin master --force

**Comment by lossyrob** [comment]
Perfect, thank you!

**Pull request merged**
