### PR TITLE
Update LazySegmentBytes to only read required segments

### PR DESCRIPTION
**Pull request by kthompson**
Previously LazySegmentBytes would read all segments between the first and
last segment causing much more data to be downloaded when the
StreamingByteReader is used.

Signed-off-by: Kevin Thompson <kevin.thompson@theautomaters.com>

### CODE REVIEW

**Comment by kthompson** [comment]
There may be a good reason this was reading the way it was so let me know if there is some rework you would like to see here.

**Comment by echeipesh** [comment]
The assumption was that that you're likely going to be reading consecutive segments and it would be good to read as many of them at once as possible to avoid additional overhead. Although I don't recall us having done rigorous testing to measure this overhead.

I'm guessing you ran into cases where that wasn't true or helpful?

**Comment by kthompson** [comment]
Yes for streaming geotiffs from S3. Using the existing method typically retrieves way more data than you actually need. From my testing it was around 10x the transfer of using something like vsicurl.

**Comment by echeipesh** [comment]
Thank you for clarification.

**Pull request merged**
