### PR TITLE
GeoTrellis-2372 Add Microsoft Azure Blob Storage Support

### PR DESCRIPTION
**Pull request by aheyne**
* Added wasb and wasbs URI schemes

Signed-off-by: Austin Heyne <aheyne@ccri.com>

Fixes #2373

### CODE REVIEW

**Comment by aheyne** [comment]
This has been tested.

**Comment by aheyne** [comment]
Write has been tested.

**Comment by metasim** [comment]
Are additional libraries necessary for this to work? Amazed this is just a one-line change!

**Comment by aheyne** [comment]
Yes, you need some additional jars and Hadoop configuration but all of that is out side of the scope of GeoTrellis. We may want some documentation around this but essentially all you need is what is outlined in the [Hadoop Azure Support](https://hadoop.apache.org/docs/stable/hadoop-azure/index.html#Accessing_wasb_URLs) documentation.

**Comment by aheyne** [comment]
Pushed some docs. Let me know if you'd like something more.

**Pull request merged**
