### PR TITLE
Allows Temporal Ingests from spark-etl to S3

### PR DESCRIPTION
**Pull request by mattfullerton**
Allows Temporal Ingests from spark-etl to S3

### CODE REVIEW

**Comment by pomadchin** [comment]
Hi @mattfullerton and sry for a long response! Can you squash your commits and sign it? 
If you haven't signed ECA yet can you do it? After that just sign all your commits via `git commit -s`, more info can be found here: https://github.com/locationtech/geotrellis/blob/master/docs/CONTRIBUTING.rst#pull-requests 
and you can reach us in our gitter channel to help you to get this contribution merged.

Also we don't plan to support this `etl` package anymore (we expect it to be dropped in `3.0`) and plan to replace it with a `pipeline` that is not documented well at the moment, but you can find more info here: https://github.com/locationtech/geotrellis/blob/master/docs/CONTRIBUTING.rst#pull-requests 

Any feedback is appreciated!

**Comment by mattfullerton** [comment]
Hey, now it took me a while to reply; sorry about that.

I have never seen entry hurdles this big for making a (minor) PR to an OS project. Nevertheless, I have tried to squash the commits to one and sign it with a GPG id, same as the email address that has also signed the ECA. I hope I did it all correctly.

**Comment by mattfullerton** [comment]
I did the sign now with -s and signed the agreement (sorry, thought I only needed to sign up on the Foundation site)

**Comment by pomadchin** [comment]
thanks @mattfullerton will merge it after CI would be happy!

**Comment by echeipesh** [comment]
Backported to `2.1` with d2e3666d62f02a5e53676a528213922b054408d7

**Pull request merged**
