### PR TITLE
Added Sum resampling method to raster.resampling

### PR DESCRIPTION
**Pull request by Charmatzis**
Does what it says: Sum method has been added for resampling.

Now the aggregate resampling methods are: 

1. Median   
2. Max    
3. Min    
4. Sum

### CODE REVIEW

**Comment by pomadchin** [comment]
Thanks @Charmatzis! Can you sign your commit? 
```git commit --amend -s && git push origin -f master```

**Comment by echeipesh** [comment]
@Charmatzis actually just adding `Signed-off-by: Christos Charmatzis xr_xarmatzis@outlook.com` to the bottom of the PR is sufficient to make ip-validation happy. I know this is silly, but if you don't mind.

**Comment by pomadchin** [comment]
@Charmatzis try to rebase on master, probably IP issue with `noreply@github.com` would go: 

```
git commit rebase -i upstream/master && git push origin -f master
```

@echeipesh there is a valid sign off by footer, looks like IP checker result is that email has no valid ECAs. Can you check it manually?

**Comment by echeipesh** [comment]
screen shot 2017-09-28 at 4 36 19 pm

Looks good, blaming ip-validation bot glitch.

**Pull request merged**
