### PR TITLE
Add `MultibandTile.safeBand`

### PR DESCRIPTION
**Pull request by fosskers**
`MultibandTile.band` should not be used unless you're absolutely sure that the band index you're calling for is valid.

### CODE REVIEW

**Comment by fosskers** [comment]
Unclear why that failed.

**Comment by echeipesh** [comment]
`getBand` would be consistent with `Map` interface, which this is closest to in my mind: `Map.get(k: K): Option[V]`.

@lossyrob @fosskers There was a naming discussion but I want to throw my 2-cents in on this one.

**Comment by lossyrob** [comment]
I like @echeipesh's suggestion

**Comment by fosskers** [comment]
I was motivated by the name of the current function, `band`, and by the trend to add `safe` to function names when it's the `Option`-yielding variant.

I hear the point about compatibility with `Map`, except that we wouldn't be matching it with `apply`:
```scala
Map[K, V]

def apply(k: K): V
```
`get` seems to imply safety in the case of `Map`, but that isn't the case with `Option` as we well know. In general, just thinking about the names, `band` and `getBand` don't portray the different in their intentions. `bandSafe` (or the original `safeBand`) does.

**Comment by lossyrob** [comment]
I buy it.

**Pull request merged**
