### PR TITLE
Remove unused allocation from CroppedTile

### PR DESCRIPTION
**Pull request by kthompson**

### CODE REVIEW

**Comment by pomadchin** [comment]
Hi @kthompson thanks a lot for fixing that! Won't you mind to check other `foreach` / `map` functions in other classes for the same issue? 

And also eclipse is unhappy with your ECA, could you please sign your commit via `git commit --amend -s` ?

**Comment by pomadchin** [comment]
Oh, it looks like you used another email for signing the ECA, or you can sign it here with a new email: https://www.eclipse.org/legal/ECA.php

**Comment by kthompson** [comment]
I am not sure what the issue is with the ECA. I have signed it but for whatever reason it doesnt "pass". I could not find any other locations with a similar issue.

**Comment by pomadchin** [comment]
@kthompson oh I see, indeed!

**Review by pomadchin — APPROVED** [review]
Thanks for a quick fix!

**Pull request merged**
